# Generated by Django 4.2.2 on 2023-06-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appchat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group_chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='GroupChat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
